name: Lint and Test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  lint:
    name: Lint template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          VALIDATE_DOCKERFILE: true
          VALIDATE_YAML: true
          VALIDATE_MARKDOWN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29

          # Optional: working directory, useful for monorepos
          working-directory: template/gomod-middleware/function
  test:
    name: Test function template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - name: Test
        run: go test -v ./...
        working-directory: ./template/gomod-middleware/function
